### PR TITLE
Fix more_info issue

### LINKED ISSUE #344: GET /content returns Internal Server Error
Log excerpt:

```
{"level":"info","time":"2020-11-05T17:33:38Z","message":"Request received - URI: /api/insights-results-aggregator/v1/content, Method: GET"}
{"level":"error","error":"json: error calling MarshalJSON for type json.RawMessage: invalid character 'F' looking for beginning of value","time":"2020-11-05T17:33:38Z","message":"handleServerError()"}
```

### PR DESCRIPTION
**Pull request by joselsegura**
# Description

Updating PRs

Fixes #344 

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Testing steps

Regular CI

### CODE REVIEW

**Review by bond95 — APPROVED** [review]

**Review by quarckster — APPROVED** [review]

File: types/types.go [hunk 1]
```diff
@@ -82,21 +82,21 @@ const (
...
-	Active          bool            `json:"active"`
-	Internal        bool            `json:"internal"`
-	Generic         string          `json:"generic"`
-	Tags            []string        `json:"tags"`
+	Module          types.RuleID   `json:"module"`
+	Name            string         `json:"name"`
+	Summary         string         `json:"summary"`
+	Reason          string         `json:"reason"`
+	Resolution      string         `json:"resolution"`
+	MoreInfo        string         `json:"more_info"`
```
Comment (Sergey1011010) [inline types/types.go:90]: are you sure it won't break markdown parsing?

Comment (joselsegura) [reply types/types.go:90]: I don't think so. Apart of that, more info files cannot be a `json.RawMessage` because more_info.md files doesn't contain any json at all, so it was failing at marshalling the response when MoreInfo contains some markdown
